apiVersion: dashboard.opendatahub.io/v1
kind: OdhDocument
metadata:
  name: agentic-starter-kits-crewai-websearch-agent-tutorial
  annotations:
    opendatahub.io/categories: 'Agent Templates,Getting started'
spec:
  type: tutorial
  displayName: 'CrewAI WebSearch Agent'
  description: >-
    Web search agent built with CrewAI using a ReAct-style crew with a web search tool to answer user questions.
  url: 'https://red.ht/4wipPNS'
  appName: agentic-starter-kits
