kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: servingruntimes-config-updater
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames:
      - servingruntimes-config
