kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-dashboard
rules:
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kfdef.apps.kubeflow.org
    resources:
      - kfdefs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    resources:
      - configmaps
      - persistentvolumeclaims
      - secrets
  - apiGroups:
      - batch
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    resources:
      - cronjobs
      - jobs
      - jobs/status
  - apiGroups:
      - image.openshift.io
    verbs:
      - create
      - get
      - list
      - update
      - patch
      - delete
    resources:
      - imagestreams
  - apiGroups:
      - build.openshift.io
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - delete
    resources:
      - builds
      - buildconfigs
      - buildconfigs/instantiate
  - verbs:
      - list
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
  - apiGroups:
      - apps.openshift.io
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    resources:
      - deploymentconfigs
      - deploymentconfigs/instantiate
  - apiGroups:
      - opendatahub.io
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    resources:
      - odhdashboardconfigs
  - apiGroups:
      - kubeflow.org
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    resources:
      - notebooks
