kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-dashboard-istio-reader
rules:
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list

