# Quality Gates Configuration for model-registry
# This file controls the behavior of the Modular Architecture Quality Gates

# Silent Mode Configuration
# When enabled, this module will not generate detailed quality gate reports
# Useful for modules that are still in development or don't need detailed reporting
silent_notifications: true

# Future Configuration Options (commented out for now)
# These will be available in future versions of the quality gates system

# test_coverage_threshold: 80
# performance_threshold: 2000ms
# bundle_size_limit: 500KB
# custom_checks:
#   - name: "Custom Security Check"
#     enabled: true
#   - name: "Accessibility Compliance"
#     enabled: false
