#!/usr/bin/env node

/**
 * Local test script for PR comment functionality
 * This simulates the exact workflow_run scenario to test PR commenting
 */

const fs = require('fs');
const path = require('path');

// Simulate GitHub context
const mockContext = {
  repo: {
    owner: 'opendatahub-io',
    repo: 'odh-dashboard'
  }
};

// Simulate GitHub API client
const mockGitHub = {
  rest: {
    repos: {
      listPullRequestsAssociatedWithCommit: async ({ owner, repo, commit_sha }) => {
        console.log(`📋 Mock API: Getting PRs for commit ${commit_sha}`);
        // Simulate finding PR #4679
        return {
          data: [{ number: 4679 }]
        };
      }
    },
    issues: {
      listComments: async ({ owner, repo, issue_number }) => {
        console.log(`📋 Mock API: Getting comments for PR #${issue_number}`);
        // Simulate existing comments (none initially)
        return {
          data: []
        };
      },
      createComment: async ({ owner, repo, issue_number, body }) => {
        console.log(`✅ Mock API: Creating comment on PR #${issue_number}`);
        console.log(`📊 Comment length: ${body.length} characters`);
        console.log(`📄 Comment preview (first 200 chars):`);
        console.log(body.substring(0, 200) + '...');
        return { data: { id: 123456 } };
      },
      updateComment: async ({ owner, repo, comment_id, body }) => {
        console.log(`✅ Mock API: Updating comment ${comment_id}`);
        console.log(`📊 Comment length: ${body.length} characters`);
        return { data: { id: comment_id } };
      }
    }
  }
};

// Simulate core.setOutput
const mockCore = {
  setOutput: (key, value) => {
    console.log(`📤 Setting output ${key} = ${value}`);
  }
};

// Test summary content generation
function generateTestSummary() {
  return `# 🚦 Modular Architecture Quality Gates Results

## 📊 Assessment Summary for \`model-registry\`

### Gate 1: Code Quality ✅ PASSED (5/5 - 100%)
| Check | Status | Details |
|-------|--------|---------|
| Package Structure | ✅ PRESENT | package.json + extensions.ts found |
| TypeScript Config | ✅ PRESENT | tsconfig.json configured |
| Shared Dependencies | ✅ PRESENT | @odh-dashboard/internal found |
| PatternFly Usage | ✅ PRESENT | @patternfly/react-core found |
| BFF Structure | ✅ COMPLIANT | go.mod + cmd/ directory |

### Gate 2: Deployment Quality ✅ PASSED (5/5 - 100%)
| Check | Status | Details |
|-------|--------|---------|
| Dockerfile | ✅ PRESENT | Container ready |
| Module Federation | ✅ CONFIGURED | Federation config found |
| ODH Extensions | ✅ PRESENT | extensions.ts ready |
| Health Endpoints | ✅ PRESENT | /health endpoints found |
| Security Config | ✅ PRESENT | Non-root user, secure base |

### Gate 3: Application Quality ⚠️ NEEDS ATTENTION (4/7 - 57%)
| Test Category | Status | Location |
|---------------|--------|----------|
| Unit Tests | ✅ PRESENT | \`frontend/packages/model-registry/upstream/frontend/src\` |
| E2E Tests | ✅ PRESENT | \`frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry\` |
| Mock Tests | ✅ PRESENT | Global mocked tests |
| Integration Tests | ❌ MISSING | - |
| Pact Testing | ❌ MISSING | Consumer contract tests needed |
| API Performance | ❌ MISSING | Load testing framework needed |
| Bundle Size | ❌ MISSING | Size monitoring not configured |

## 🎯 Overall Assessment

- **Deployment Ready**: ✅ **YES** (Architecture compliant, containerized)
- **ODH Integration**: ✅ **READY** (Extensions configured)  
- **RHOAI Integration**: ✅ **READY** (Security compliant)

## 📋 Next Steps

### High Priority
1. **Add Integration Tests** - Test module integration with ODH Dashboard
2. **Implement Pact Testing** - Consumer-driven contract tests for APIs

### Medium Priority  
3. **API Performance Testing** - Load testing with k6 or similar
4. **Bundle Size Monitoring** - Implement size-limit or bundlewatch

---
*Generated by Modular Architecture Quality Gates v1.0*`;
}

// Simulate the exact workflow logic
async function testWorkflowLogic() {
  console.log('🔍 TESTING PR COMMENT WORKFLOW LOGIC');
  console.log('===================================');
  
  try {
    // Step 1: Get PR number from workflow run
    console.log('\n📋 Step 1: Getting PR number from commit SHA...');
    const commit_sha = 'f03711fb0c123456789abcdef'; // Mock commit SHA
    
    const pullRequests = await mockGitHub.rest.repos.listPullRequestsAssociatedWithCommit({
      owner: mockContext.repo.owner,
      repo: mockContext.repo.repo,
      commit_sha: commit_sha
    });
    
    if (pullRequests.data.length === 0) {
      console.log('❌ No PR found for this workflow run');
      return;
    }
    
    const prNumber = pullRequests.data[0].number;
    console.log(`📋 Found PR #${prNumber}`);
    mockCore.setOutput('pr-number', prNumber);
    
    // Step 2: Read quality gates summary
    console.log('\n📄 Step 2: Reading quality gates summary...');
    let summaryContent = '';
    
    // Simulate reading from artifact
    try {
      summaryContent = generateTestSummary();
      console.log('✅ Successfully generated quality gates summary');
      console.log(`📊 Summary length: ${summaryContent.length} characters`);
    } catch (error) {
      console.log('❌ Failed to generate summary:', error.message);
      summaryContent = '## 🚦 Quality Gates Summary\\n\\n❌ Unable to load summary content. Please check the workflow logs.';
    }
    
    // Step 3: Post or update PR comment
    console.log('\n💬 Step 3: Posting comment to PR...');
    
    try {
      // Check for existing quality gates comments
      const comments = await mockGitHub.rest.issues.listComments({
        owner: mockContext.repo.owner,
        repo: mockContext.repo.repo,
        issue_number: prNumber
      });
      
      const botComment = comments.data.find(comment => 
        comment.user && comment.user.type === 'Bot' && 
        comment.body && comment.body.includes('🚦 Modular Architecture Quality Gates Results')
      );
      
      if (botComment) {
        // Update existing comment
        await mockGitHub.rest.issues.updateComment({
          owner: mockContext.repo.owner,
          repo: mockContext.repo.repo,
          comment_id: botComment.id,
          body: summaryContent
        });
        console.log('✅ Updated existing quality gates comment');
      } else {
        // Create new comment
        await mockGitHub.rest.issues.createComment({
          owner: mockContext.repo.owner,
          repo: mockContext.repo.repo,
          issue_number: prNumber,
          body: summaryContent
        });
        console.log('✅ Created new quality gates comment');
      }
      
      console.log('\n🎉 PR COMMENT TEST COMPLETED SUCCESSFULLY!');
      console.log('The workflow logic appears to be working correctly.');
      
    } catch (error) {
      console.log('❌ Failed to post comment:', error.message);
      console.log('📊 Error details:', error);
      
      // Test fallback
      console.log('\n🔄 Testing fallback comment...');
      try {
        await mockGitHub.rest.issues.createComment({
          owner: mockContext.repo.owner,
          repo: mockContext.repo.repo,
          issue_number: prNumber,
          body: '## 🚦 Quality Gates Summary\\n\\n❌ Failed to post detailed summary. Check workflow logs for details.'
        });
        console.log('✅ Posted fallback comment');
      } catch (fallbackError) {
        console.log('❌ Fallback comment also failed:', fallbackError.message);
      }
    }
    
  } catch (error) {
    console.error('💥 CRITICAL ERROR in workflow logic:', error);
  }
}

// Test different scenarios
async function runAllTests() {
  console.log('🧪 COMPREHENSIVE PR COMMENT TESTING');
  console.log('===================================');
  
  console.log('\n🔬 Test 1: Normal workflow scenario');
  await testWorkflowLogic();
  
  console.log('\n🔬 Test 2: Artifact reading simulation');
  const testSummary = generateTestSummary();
  console.log('Generated summary preview:');
  console.log('---');
  console.log(testSummary.substring(0, 500) + '...');
  console.log('---');
  
  console.log('\n✅ All tests completed!');
  console.log('\n🎯 RECOMMENDATIONS:');
  console.log('1. The workflow logic structure is correct');
  console.log('2. GitHub API calls are properly formatted'); 
  console.log('3. Error handling includes fallback mechanisms');
  console.log('4. Summary content generation works as expected');
  console.log('\n⚠️  POTENTIAL ISSUES TO CHECK:');
  console.log('1. Verify GITHUB_TOKEN has pull-requests: write permission');
  console.log('2. Confirm workflow_run trigger is working correctly');  
  console.log('3. Check artifact upload/download is successful');
  console.log('4. Ensure PR number detection is accurate in CI environment');
}

// Run the tests
runAllTests().catch(console.error);
