apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspaces-controller
spec:
  replicas: 1
  selector:
    matchLabels: {}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels: {}
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
        - "--leader-elect"
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=0"
        image: workspaces-controller
        imagePullPolicy: IfNotPresent
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65532
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - name: http
          containerPort: 8081
        - name: https-webhook
          containerPort: 9443
        ##
        ## TODO: finalize the default resource requests and limits for the controller/webook container
        ##
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: workspaces-controller
      terminationGracePeriodSeconds: 10
