const path = require('path');
const { rspack } = require('@rspack/core');
const { discoverPluginPackages } = require('./discoverPluginPackages');

/**
 * Rspack plugin that virtually overrides plugin-extensions.ts with imports for
 * all discovered plugin packages. Uses rspack's built-in VirtualModulesPlugin
 * so nothing is written to disk.
 */
class GenerateExtensionsPlugin {
  /**
   * @param {{ modulePath: string }} options Absolute path of the stub module to override.
   */
  constructor(options) {
    this.modulePath = options.modulePath;
  }

  apply(compiler) {
    const discoveredPackages = discoverPluginPackages();
    console.log('Extension packages:', discoveredPackages);

    const relativePath = path.relative(compiler.context, this.modulePath);
    const content = this.generateFileContent(discoveredPackages);

    new rspack.experiments.VirtualModulesPlugin({
      [relativePath]: content,
    }).apply(compiler);
  }

  generateFileContent(pluginPackages) {
    if (!pluginPackages || pluginPackages.length === 0) {
      return `import type { Extension } from '@openshift/dynamic-plugin-sdk';

// This file gets auto-generated by the build process.
// Dynamically populated with packages that export extensions.
const pluginExtensions: Record<string, Extension[]> = {};

export default pluginExtensions;
`;
    }

    const imports = pluginPackages
      .map((pkgName, index) => `import extensions${index} from '${pkgName}/extensions';`)
      .join('\n');

    const recordEntries = pluginPackages
      .map((pkgName, index) => `  '${pkgName}': extensions${index}`)
      .join(',\n');

    return `import type { Extension } from '@openshift/dynamic-plugin-sdk';
${imports}

// This file gets auto-generated by the build process.
// Dynamically populated with packages that export extensions.
const pluginExtensions: Record<string, Extension[]> = {
${recordEntries},
};

export default pluginExtensions;
`;
  }
}

module.exports = GenerateExtensionsPlugin;
