apiVersion: v1
kind: ConfigMap
metadata:
  name: federation-config
data:
  module-federation-config.json: |
    [
      {
        "name": "modelRegistry",
        "remoteEntry": "/remoteEntry.js",
        "authorize": true,
        "tls": false,
        "proxy": [
          {
            "path": "/model-registry/api",
            "pathRewrite": "/api"
          }
        ],
        "local": {
          "host": "localhost",
          "port": 8080
        },
        "service": {
          "name": "model-registry-ui-service",
          "namespace": "opendatahub",
          "port": 8080
        }
      }
    ]
