kind: Service
apiVersion: v1
metadata:
  name: odh-dashboard
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: dashboard-proxy-tls
spec:
  selector:
    deployment: odh-dashboard
  ports:
    - name: dashboard-ui
      protocol: TCP
      port: 8443
      targetPort: 8443
