apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app: odh-dashboard
      app.kubernetes.io/part-of: odh-dashboard

resources:
  - ./jupyter
