apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maas-portal-rhods-operator-subscription
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: maas-portal-rhods-operator-subscription
subjects:
  - kind: ServiceAccount
    name: maas-portal
    namespace: dashboard-namespace
