export enum TrainingJobState {
  CREATED = 'Created',
  PENDING = 'Pending',
  QUEUED = 'Queued',
  RUNNING = 'Running',
  RESTARTING = 'Restarting',
  SUCCEEDED = 'Succeeded',
  FAILED = 'Failed',
  PAUSED = 'Paused',
  RESUMING = 'Resuming',
  SUSPENDED = 'Suspended',
  PREEMPTED = 'Preempted',
  INADMISSIBLE = 'Inadmissible',
  DELETING = 'Deleting',
  UNKNOWN = 'Unknown',
}
