# LLMInferenceService with hidden OCI Connection (via Connections API)
# Requires: connections/hidden-oci-connection.yaml
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: llm-hidden-oci-conn
  annotations:
    opendatahub.io/connections: secret-oci456
spec:
  model:
    name: my-model
    uri: oci://quay.io/private-repo/model-image:v1
  replicas: 1
  router:
    gateway: {}
    route: {}
    scheduler: {}
  template:
    # webhook will populate this
    # imagePullSecrets:
    #   - name: secret-oci456
    containers:
      - name: main
