# LLMInferenceService with missing/non-existent PVC
# Negative test case - the referenced PVC does not exist
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: llm-missing-pvc
spec:
  model:
    name: my-model
    uri: pvc://nonexistent-pvc/path/to/model
  replicas: 1
  router:
    gateway: {}
    route: {}
    scheduler: {}
  template:
    containers:
      - name: main
