## the ServiceAccount used by all WorkspaceKinds
##  - the name is hardcoded in the controller, so it MUST stay "default-editor"
##  - the controller will NOT create it, one MUST exist in every Namespace
##    where Workspaces are created
##  - see https://github.com/kubeflow/notebooks/issues/1257
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-editor