name: E2E Tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - notebooks-v2
      - v*-branch
  pull_request:
    paths:
      - workspaces/**

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Kind
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          config: ./testing/kind-1-35.yaml
          cluster_name: "local-e2e"

      - name: Install Cluster Dependencies
        run: make setup-cluster

      - name: Deploy Kubeflow Workspaces
        run: make deploy-all

      - name: Verify Deployment
        run: make sanity-check

      - name: Run local-e2e tests
        run: make local-e2e
