kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-dashboard-data-registry-ui
rules:
  - apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
