apiVersion: v1
kind: Service
metadata:
  name: odh-dashboard-data-registry-ui
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: data-registry-proxy-tls
    service.beta.kubernetes.io/backend-protocol: HTTPS
spec:
  selector:
    deployment: data-registry-ui
  ports:
    - name: data-registry-ui
      protocol: TCP
      port: 9043
      targetPort: 9043
