name: (Internal) Test Template
description: Intended to help with a template for creating issues for test coverage.
title: "[Test]: "
labels: ["kind/tech-debt", "priority/normal", "quality"]
body:
  - type: input
    id: description
    attributes:
      label: Description
      description: A high level goal for the test.
      placeholder: Tests the global <feature> page.
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: What type of test is it?
      multiple: false
      options:
        - e2e (user flow, server data test)
        - integration (test data, UI rendering)
        - unit (functional test)
    validations:
      required: true
  - type: textarea
    id: goals
    attributes:
      label: Test goals
      description: |
        Describe the test coverage goals / acceptance criteria.

        Eg. what tests are expected / what is the full path for e2e test / what utils are to be tested / etc
      placeholder: |
        * Test page xyz
        * Handle empty states
        * etc...
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Related tests
      description: |
        A link to related test stories to help with sizing the work

        Tip: Using a bullet list will help display links to other tickets by unraveling the name and status of that ticket.
      placeholder: |
        * #xxxx1
        * #xxxx2
      value: No related tests
    validations:
      required: false
