import * as React from 'react';
import { ModelCatalogAPIState } from '~/app/hooks/modelCatalog/useModelCatalogAPIState';
import { CatalogFilterOptionsList, CatalogLabelList, CatalogSource, CatalogSourceList, ModelCatalogFilterStates } from '~/app/modelCatalogTypes';
import { ModelCatalogSortOption } from '~/concepts/modelCatalog/const';
export type ModelCatalogContextType = {
    catalogSourcesLoaded: boolean;
    catalogSourcesLoadError?: Error;
    catalogSources: CatalogSourceList | null;
    catalogLabels: CatalogLabelList | null;
    catalogLabelsLoaded: boolean;
    catalogLabelsLoadError?: Error;
    selectedSource: CatalogSource | undefined;
    updateSelectedSource: (source: CatalogSource | undefined) => void;
    selectedSourceLabel: string | undefined;
    updateSelectedSourceLabel: (sourceLabel: string | undefined) => void;
    apiState: ModelCatalogAPIState;
    refreshAPIState: () => void;
    filterData: ModelCatalogFilterStates;
    setFilterData: <K extends keyof ModelCatalogFilterStates>(key: K, value: ModelCatalogFilterStates[K]) => void;
    filterOptions: CatalogFilterOptionsList | null;
    filterOptionsLoaded: boolean;
    filterOptionsLoadError?: Error;
    performanceViewEnabled: boolean;
    setPerformanceViewEnabled: (enabled: boolean) => void;
    performanceFiltersChangedOnDetailsPage: boolean;
    setPerformanceFiltersChangedOnDetailsPage: (changed: boolean) => void;
    lastViewedModelName: string | null;
    setLastViewedModelName: (modelName: string | null) => void;
    clearAllFilters: () => void;
    resetPerformanceFiltersToDefaults: () => void;
    resetSinglePerformanceFilterToDefault: (filterKey: keyof ModelCatalogFilterStates) => void;
    getPerformanceFilterDefaultValue: (filterKey: keyof ModelCatalogFilterStates) => string | number | string[] | undefined;
    sortBy: ModelCatalogSortOption | null;
    setSortBy: (sortBy: ModelCatalogSortOption | null) => void;
};
type ModelCatalogContextProviderProps = {
    children: React.ReactNode;
};
export declare const ModelCatalogContext: React.Context<ModelCatalogContextType>;
export declare const ModelCatalogContextProvider: React.FC<ModelCatalogContextProviderProps>;
export {};
