apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspaces-controller
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8443"
    spec:
      containers:
      - name: manager
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        args:
        - "--leader-elect"
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=:8443"
        volumeMounts:
        - name: metrics-certs
          mountPath: /tmp/k8s-metrics-server/metrics-certs
          readOnly: true
      volumes:
      - name: metrics-certs
        secret:
          secretName: workspaces-controller-metrics-tls
          optional: false
