apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: odh-dashboard
  app.kubernetes.io/part-of: odh-dashboard
resources:
  - ovms-ootb.yaml
  - caikit-ootb.yaml
  - tgis-ootb.yaml
  - ovms-kserve-ootd.yaml
images:
  - name: ovms-1
    newName: quay.io/opendatahub/openvino_model_server
    digest: sha256:ccfce13c89c4ddfd31e6c56fc35fd46afe10c2d3d3998ab1c2bf14448fdd389f
  - name: caikit-tgis-serving
    newName: quay.io/opendatahub/caikit-tgis-serving
    digest: sha256:45c0ec470999b2ce3cd0b43192d9cba88aab403a3dd58da40c14a5c9ccade8d0
  - name: text-generation-inference
    newName: quay.io/opendatahub/text-generation-inference
    digest: sha256:7599c47920b3ab572b019f21760c52b7bc59f02f48da4f2bf68e691eeb349e3f
  - name: ovms-kserve
    newName: quay.io/opendatahub/openvino_model_server
    digest: sha256:ccfce13c89c4ddfd31e6c56fc35fd46afe10c2d3d3998ab1c2bf14448fdd389f
