kind: ConfigMap
apiVersion: v1
metadata:
  name: oci-v1
  labels:
    opendatahub.io/connection-type: 'true'
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/description: 'Connect to an OCI-compliant container registry, enabling integration with containerized applications and services. Use this connection type to pull and manage container images and artifacts that adhere to the Open Container Initiative (OCI) standards, ensuring compatibility with OCI-compliant tools and workflows.'
    openshift.io/display-name: OCI compliant registry - v1
data:
  category: '["Container registry"]'
  fields: '[{"type":"dropdown","name":"Access type","description":"Access type can be push (push for uploading data), pull (pull for accessing resources), or both depending on the use case. E.g. Pull/both for deploying a model, push/both for InstructLab fine-tune runs.","envVar":"ACCESS_TYPE","required":false,"properties":{"variant":"multi","items":[{"label":"Push secret","value":"Push"},{"label":"Pull secret","value":"Pull"}]}},{"type":"file","name":"Secret details","envVar":".dockerconfigjson","required":true,"properties":{"extensions":[".dockerconfigjson",".json"],"helperText":"Be cautious when sharing sensitive information. Secret details are visible to users with access to the project. Users with access to this connection can access the repositories associated with the pull secret."}},{"type":"short-text","name":"Base URL / Registry URI","envVar":"OCI_HOST","required":true,"properties":{}}]'
