apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesJson6902:
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: odh-dashboard
