apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - role.yaml
  - role-binding.yaml

configMapGenerator:
  - name: core-bff-params
    env: params.env

generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: rhaii-dashboard-image
    objref:
      kind: ConfigMap
      name: core-bff-params
      apiVersion: v1
    fieldref:
      fieldpath: data.rhaii-dashboard-image

configurations:
  - params.yaml
