apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rhaii-dashboard
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups:
      - opendatahub.io
    resources:
      - odhdashboardconfigs
    verbs:
      - get
      - create
      - patch
  - apiGroups:
      - dashboard.opendatahub.io
    resources:
      - odhapplications
    verbs:
      - list
