apiVersion: v1
kind: Service
metadata:
  name: rhaii-dashboard
  labels:
    app.kubernetes.io/name: rhaii-dashboard
    app.kubernetes.io/part-of: odh-dashboard
spec:
  selector:
    deployment: rhaii-dashboard
  ports:
    - name: core-bff-api
      protocol: TCP
      port: 4000
      targetPort: 4000
