apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

labels:
- includeSelectors: false # avoid adding the webhook component label to the Service selector, so it matches the manager pod labels
  pairs:
    app.kubernetes.io/component: webhook
