apiVersion: v1
kind: Service
metadata:
  name: workspaces-webhook-service
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: https-webhook
  selector:
    # NOTE: these are the labels from the `manager` base because we currently only have one deployment for both the webhook and controller
    app: workspaces-controller
    app.kubernetes.io/component: controller-manager
