apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./aikit
  - ./elastic
  - ./jupyter
  - ./nvidia-nim
  - ./openvino
  - ./pachyderm
  - ./pgvector
  - ./rhoai
  - ./starburst-enterprise
  - ./watson-x
