import * as React from 'react';
import type { MlflowExperiment } from '@odh-dashboard/internal/concepts/mlflow';
import type { Collection, FlatBenchmark, InferenceServiceItem, ModelSelection, SourceMode } from '~/app/types';
type ExperimentMode = 'existing' | 'new';
declare const DEFAULT_EXPERIMENT_NAME = "EvalHub";
export declare const EXTERNAL_ENDPOINT_VALUE = "__external__";
type UseStartEvaluationRunFormParams = {
    namespace: string | undefined;
    benchmark: FlatBenchmark | undefined;
    collection: Collection | undefined;
    isCollectionFlow: boolean;
    experiments: MlflowExperiment[];
    experimentsLoaded: boolean;
};
export declare function useStartEvaluationRunForm({ namespace, benchmark, collection, isCollectionFlow, experiments, experimentsLoaded, }: UseStartEvaluationRunFormParams): {
    evaluationName: string;
    setEvaluationName: React.Dispatch<React.SetStateAction<string>>;
    sourceMode: SourceMode;
    handleSourceModeChange: (mode: SourceMode) => void;
    modelSelection: ModelSelection;
    selectedInferenceService: InferenceServiceItem | undefined;
    handleModelDropdownSelect: (value: string | undefined, inferenceServices: InferenceServiceItem[]) => void;
    modelName: string;
    setModelName: React.Dispatch<React.SetStateAction<string>>;
    agentName: string;
    setAgentName: React.Dispatch<React.SetStateAction<string>>;
    endpointUrl: string;
    setEndpointUrl: React.Dispatch<React.SetStateAction<string>>;
    apiKeySecretRef: string;
    setApiKeySecretRef: React.Dispatch<React.SetStateAction<string>>;
    sourceName: string;
    setSourceName: React.Dispatch<React.SetStateAction<string>>;
    datasetUrl: string;
    setDatasetUrl: React.Dispatch<React.SetStateAction<string>>;
    accessToken: string;
    setAccessToken: React.Dispatch<React.SetStateAction<string>>;
    experimentMode: ExperimentMode;
    setExperimentMode: React.Dispatch<React.SetStateAction<ExperimentMode>>;
    selectedExperiment: MlflowExperiment | undefined;
    setSelectedExperiment: React.Dispatch<React.SetStateAction<MlflowExperiment | undefined>>;
    newExperimentName: string;
    setNewExperimentName: React.Dispatch<React.SetStateAction<string>>;
    experimentManuallyChangedRef: React.MutableRefObject<boolean>;
    showAdditionalArgs: boolean;
    setShowAdditionalArgs: React.Dispatch<React.SetStateAction<boolean>>;
    additionalArgs: string;
    additionalArgsFilename: string;
    handleAdditionalArgsFileChange: (_event: React.DragEvent<HTMLElement> | React.ChangeEvent<HTMLInputElement> | Event, file: File) => void;
    handleAdditionalArgsTextChange: (_event: React.ChangeEvent<HTMLTextAreaElement>, value: string) => void;
    handleAdditionalArgsClear: () => void;
    isSubmitting: boolean;
    isValid: boolean;
    handleSubmit: () => Promise<void>;
    handleCancel: () => void;
    benchmarkDisplayName: string;
    isCollectionFlow: boolean;
    threshold: number;
    handleThresholdChange: (value: number) => void;
    availableMetrics: string[];
    primaryMetric: string | undefined;
    handlePrimaryMetricChange: (metric: string) => void;
    touched: Record<string, boolean>;
    markTouched: (field: string) => void;
    endpointUrlError: string | undefined;
    datasetUrlError: string | undefined;
    connectionValidation: import("~/app/types").ConnectionValidationState;
    handleVerifyConnection: () => Promise<void>;
    canVerifyConnection: boolean;
    requiresConnectionValidation: boolean;
};
export declare const EXPERIMENT_FILTER = "tags.context = 'eval-hub'";
export { DEFAULT_EXPERIMENT_NAME };
