apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agentic-starter-kits-app.yaml
  - agentic-starter-kits-langgraph-tutorial.yaml
  - agentic-starter-kits-llamaindex-tutorial.yaml
  - agentic-starter-kits-vanilla-python-tutorial.yaml
  - agentic-starter-kits-rag-tutorial.yaml
  - agentic-starter-kits-crewai-tutorial.yaml
  - agentic-starter-kits-autogen-tutorial.yaml
  - agentic-starter-kits-langflow-tutorial.yaml
  - agentic-starter-kits-memory-tutorial.yaml
  - agentic-starter-kits-a2a-tutorial.yaml
  - agentic-starter-kits-google-adk-tutorial.yaml
  - agentic-starter-kits-hitl-tutorial.yaml
