apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: sentinel-cluster-queue
spec:
  namespaceSelector:
    matchLabels:
      kueue.openshift.io/managed: "true"
  queueingStrategy: BestEffortFIFO
  resourceGroups:
    - coveredResources:
        - cpu
        - memory
      flavors:
        - name: sentinel-default
          resources:
            - name: cpu
              nominalQuota: "4"
            - name: memory
              nominalQuota: 8Gi
