export const PIPELINE_LAYOUT = 'PipelineLayout';
export const PIPELINE_NODE_SEPARATION_VERTICAL = 70;
export const PIPELINE_NODE_SEPARATION_HORIZONTAL = 150;

export const NODE_WIDTH = 130;
export const NODE_HEIGHT = 35;

export const EXECUTION_TASK_NODE_TYPE = 'EXECUTION_TASK_NODE';
