apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# NOTE: we use this namespace for consistency with kube-prometheus:
#       https://github.com/prometheus-operator/kube-prometheus/blob/v0.18.0/manifests/prometheus-prometheus.yaml#L11
namespace: monitoring

resources:
- rbac.yaml
- prometheus.yaml