apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    ## NOTE: we use "restricted" because `kubeflow/manifests` also sets this on the kubeflow namespace:
    ##       https://github.com/kubeflow/manifests/blob/26.03/common/kubeflow-namespace/base/kubeflow/namespace.yaml
    pod-security.kubernetes.io/enforce: restricted