version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    gocritic:
      disabled-checks:
        - assignOp
        - filepathJoin
        - paramTypeCombine
        - rangeValCopy
        - unnamedResult
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    goheader:
      template: |-
        Copyright 2024.

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    misspell:
      locale: US
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - dupl
          - errcheck
          - goconst
          - gocyclo
          - gosec
        path: test/.*|.*_test\.go
      - linters:
          - gocritic
        text: 'importShadow: shadow of imported from ''sigs.k8s.io/controller-runtime/pkg/log'' package ''log'''
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kubeflow/notebooks/workspaces/controller
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
