apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendatahub

resources:
- ../../../core-bff/manifests/base
- api-tester.yaml

patches:
- target:
    kind: Deployment
    name: rhaii-dashboard
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rhaii-dashboard
    spec:
      template:
        spec:
          containers:
            - name: rhaii-dashboard
              env:
                - name: DEV_MODE
                  value: "true"
