# Direct pull secret - user-created, not a Dashboard Connection
# Used for testing direct imagePullSecrets references
apiVersion: v1
kind: Secret
metadata:
  name: direct-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "quay.io": {
          "username": "directuser",
          "password": "directpass",
          "auth": "ZGlyZWN0dXNlcjpkaXJlY3RwYXNz"
        }
      }
    }
