apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maas-consumer-portal
rules:
  - apiGroups:
      - datasciencecluster.opendatahub.io
    resources:
      - datascienceclusters
    verbs:
      - get
      - list
  - apiGroups:
      - config.openshift.io
    resources:
      - ingresses
    verbs:
      - get
