apiVersion: v1
kind: Service
metadata:
  name: maas-consumer-portal
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: maas-consumer-portal-tls
    service.beta.kubernetes.io/backend-protocol: HTTPS
spec:
  selector:
    deployment: maas-consumer-portal
  ports:
    - name: portal-ui
      protocol: TCP
      port: 8443
      targetPort: 8443
