import type { Extension } from '@openshift/dynamic-plugin-sdk';

// This file gets auto-generated by the build process.
// Dynamically populated with packages that export extensions.
const pluginExtensions: Record<string, Extension[]> = {};

export default pluginExtensions;
