/* eslint-disable no-barrel-files/no-barrel-files */
// eslint-disable-next-line @odh-dashboard/no-restricted-imports -- re-exporting from ui-core for backward compatibility
export {
  HardwareProfileIcon,
  ApiKeysAndSubscriptionsIcon,
  ArtifactIcon,
  BuildIcon,
  ClusterSettingsIcon,
  ConfigurationIcon,
  CreateAndTrainIcon,
  DataConnectionIcon,
  DeployedModelIcon,
  DistributedWorkloadIcon,
  EnabledApplicationsIcon,
  ExperimentIcon,
  ExploreApplicationsIcon,
  GroupIcon,
  ModelIcon,
  McpCatalogIcon,
  AgentOpsIcon,
  ModelCatalogIcon,
  ModelEvaluationIcon,
  ModelRegistryIcon,
  ModelRegistrySelectIcon,
  ModelServerIcon,
  MultiModelIcon,
  NotebookIcon,
  NotebookImageIcon,
  PermissionsIcon,
  CheckmarkIcon,
  PipelineIcon,
  PipelineRunIcon,
  ProjectIcon,
  RegisteredModelIcon,
  ResourcesIcon,
  RhUiTagIcon,
  ScrewWrenchIcon,
  ServingRuntimeIcon,
  SingleModelIcon,
  StorageClassIcon,
  StorageIcon,
  UserIcon,
  LabTuningIcon,
  ModelConnectionRocketIcon,
  PromptManagementIcon,
  ChecklistIcon,
} from '@odh-dashboard/ui-core/design/icons';
