apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: rhods-dashboard
  app.kubernetes.io/part-of: rhods-dashboard
resources:
  - ../shared
  - ./apps
configMapGenerator:
  - name: rhoai-dashboard-params
    env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
  - name: odh-dashboard-image
    objref:
      kind: ConfigMap
      name: rhoai-dashboard-params
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-dashboard-image
  - name: kube-rbac-proxy
    objref:
      kind: ConfigMap
      name: rhoai-dashboard-params
      apiVersion: v1
    fieldref:
      fieldpath: data.kube-rbac-proxy
  - name: section-title
    objref:
      kind: ConfigMap
      name: rhoai-dashboard-params
      apiVersion: v1
    fieldref:
      fieldpath: data.section-title
  - name: dashboard-url
    objref:
      kind: ConfigMap
      name: rhoai-dashboard-params
      apiVersion: v1
    fieldref:
      fieldpath: data.dashboard-url
  - name: gateway-name
    objref:
      kind: ConfigMap
      name: rhoai-dashboard-params
      apiVersion: v1
    fieldref:
      fieldpath: data.gateway-name
configurations:
  - params.yaml
