package maas

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/opendatahub-io/gen-ai/internal/models"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// capturedRequest holds the HTTP request details captured by the fake server.
type capturedRequest struct {
	Method string
	Path   string
	Header http.Header
	Body   map[string]interface{}
}

// newFakeServer creates an httptest server that captures request details and
// responds with the given status code and body.
func newFakeServer(t *testing.T, statusCode int, responseBody string) (*httptest.Server, *capturedRequest) {
	t.Helper()
	captured := &capturedRequest{}

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		captured.Method = r.Method
		captured.Path = r.URL.Path
		captured.Header = r.Header.Clone()

		body, err := io.ReadAll(r.Body)
		require.NoError(t, err)
		defer r.Body.Close()

		if len(body) > 0 {
			captured.Body = make(map[string]interface{})
			require.NoError(t, json.Unmarshal(body, &captured.Body))
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(statusCode)
		_, _ = w.Write([]byte(responseBody))
	}))

	return server, captured
}

// successResponse is a fixed test fixture; the date is arbitrary and not validated by these tests.
const successResponse = `{"key":"sk-oai-test-key","expiresAt":"2099-01-01T00:00:00Z"}`

func TestIssueToken_AlwaysSetsEphemeral(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	assert.Equal(t, true, captured.Body["ephemeral"])
}

func TestIssueToken_DefaultTTL(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	assert.Equal(t, "1h", captured.Body["expiresIn"])
}

func TestIssueToken_PreservesCallerTTL(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{
		ExpiresIn: "30m",
	})
	require.NoError(t, err)

	assert.Equal(t, "30m", captured.Body["expiresIn"])
}

func TestIssueToken_NoAutoGeneratedName(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	_, namePresent := captured.Body["name"]
	assert.False(t, namePresent, "name field should be absent (omitempty) when caller does not set it")
}

func TestIssueToken_EphemeralOverridesCallerFalse(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{
		Ephemeral: false,
	})
	require.NoError(t, err)

	assert.Equal(t, true, captured.Body["ephemeral"],
		"client must override caller's Ephemeral=false to true")
}

func TestIssueToken_PostsToCorrectEndpoint(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	assert.Equal(t, http.MethodPost, captured.Method)
	assert.Equal(t, "/v1/api-keys", captured.Path)
}

func TestIssueToken_SetsAuthHeader(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "test-bearer-token", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	assert.Equal(t, "Bearer test-bearer-token", captured.Header.Get("Authorization"))
	assert.Equal(t, "application/json", captured.Header.Get("Content-Type"))
}

func TestIssueToken_HandlesServerError(t *testing.T) {
	server, _ := newFakeServer(t, http.StatusInternalServerError, `{"error":"internal"}`)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	resp, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})

	assert.Nil(t, resp)
	require.Error(t, err)

	maasErr, ok := err.(*MaaSError)
	require.True(t, ok, "error should be a *MaaSError")
	assert.Equal(t, ErrCodeServerUnavailable, maasErr.Code)
}

func TestIssueToken_HandlesClientError(t *testing.T) {
	server, _ := newFakeServer(t, http.StatusBadRequest, `{"error":"bad request"}`)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	resp, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})

	assert.Nil(t, resp)
	require.Error(t, err)

	maasErr, ok := err.(*MaaSError)
	require.True(t, ok, "error should be a *MaaSError")
	assert.Equal(t, ErrCodeInvalidResponse, maasErr.Code)
}

func TestIssueToken_ForwardsSubscription(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{
		Subscription: "premium-subscription",
	})
	require.NoError(t, err)

	assert.Equal(t, "premium-subscription", captured.Body["subscription"])
}

func TestIssueToken_OmitsSubscriptionWhenEmpty(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	_, subscriptionPresent := captured.Body["subscription"]
	assert.False(t, subscriptionPresent, "subscription field should be absent (omitempty) when not set")
}

func TestIssueToken_HandlesSuccessResponse(t *testing.T) {
	server, _ := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	resp, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	assert.Equal(t, "sk-oai-test-key", resp.Key)
	assert.Equal(t, "2099-01-01T00:00:00Z", resp.ExpiresAt)
}

func TestListModels_SendsReturnAllModelsHeader(t *testing.T) {
	var capturedHeaders http.Header
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedHeaders = r.Header.Clone()
		w.WriteHeader(http.StatusOK)
		resp := models.MaaSModelsResponse{
			Object: "list",
			Data: []models.MaaSModel{
				{
					ID:      "test-model",
					Object:  "model",
					Created: 1672531200,
					OwnedBy: "test-ns",
					Ready:   true,
					URL:     "https://test.example.com/v1",
					Subscriptions: []models.SubscriptionInfo{
						{Name: "basic-sub", DisplayName: "Basic"},
						{Name: "premium-sub", DisplayName: "Premium", Description: "Higher limits"},
					},
				},
			},
		}
		_ = json.NewEncoder(w).Encode(resp)
	}))
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "", false, nil)
	result, err := client.ListModels(context.Background(), "test-auth-token")

	require.NoError(t, err)
	assert.Equal(t, "true", capturedHeaders.Get("X-Maas-Return-All-Models"))
	assert.Equal(t, "Bearer test-auth-token", capturedHeaders.Get("Authorization"))
	require.Len(t, result, 1)
	assert.Equal(t, "test-model", result[0].ID)
	require.Len(t, result[0].Subscriptions, 2)
	assert.Equal(t, "basic-sub", result[0].Subscriptions[0].Name)
	assert.Equal(t, "Premium", result[0].Subscriptions[1].DisplayName)
	assert.Equal(t, "Higher limits", result[0].Subscriptions[1].Description)
}

func TestListModels_HandlesEmptySubscriptions(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		resp := models.MaaSModelsResponse{
			Object: "list",
			Data: []models.MaaSModel{
				{
					ID:      "no-sub-model",
					Object:  "model",
					Created: 1672531200,
					OwnedBy: "test-ns",
					Ready:   true,
					URL:     "https://test.example.com/v1",
				},
			},
		}
		_ = json.NewEncoder(w).Encode(resp)
	}))
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "", false, nil)
	result, err := client.ListModels(context.Background(), "test-auth-token")

	require.NoError(t, err)
	require.Len(t, result, 1)
	assert.Nil(t, result[0].Subscriptions)
}
