package maas

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/opendatahub-io/gen-ai/internal/models"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// capturedRequest holds the HTTP request details captured by the fake server.
type capturedRequest struct {
	Method string
	Path   string
	Header http.Header
	Body   map[string]interface{}
}

// newFakeServer creates an httptest server that captures request details and
// responds with the given status code and body.
func newFakeServer(t *testing.T, statusCode int, responseBody string) (*httptest.Server, *capturedRequest) {
	t.Helper()
	captured := &capturedRequest{}

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		captured.Method = r.Method
		captured.Path = r.URL.Path
		captured.Header = r.Header.Clone()

		body, err := io.ReadAll(r.Body)
		require.NoError(t, err)
		defer r.Body.Close()

		if len(body) > 0 {
			captured.Body = make(map[string]interface{})
			require.NoError(t, json.Unmarshal(body, &captured.Body))
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(statusCode)
		_, _ = w.Write([]byte(responseBody))
	}))

	return server, captured
}

// successResponse is a fixed test fixture; the date is arbitrary and not validated by these tests.
const successResponse = `{"key":"sk-oai-test-key","expiresAt":"2099-01-01T00:00:00Z"}`

func TestIssueToken_AlwaysSetsEphemeral(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	assert.Equal(t, true, captured.Body["ephemeral"])
}

func TestIssueToken_DefaultTTL(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	assert.Equal(t, "1h", captured.Body["expiresIn"])
}

func TestIssueToken_PreservesCallerTTL(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{
		ExpiresIn: "30m",
	})
	require.NoError(t, err)

	assert.Equal(t, "30m", captured.Body["expiresIn"])
}

func TestIssueToken_NoAutoGeneratedName(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	_, namePresent := captured.Body["name"]
	assert.False(t, namePresent, "name field should be absent (omitempty) when caller does not set it")
}

func TestIssueToken_EphemeralOverridesCallerFalse(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{
		Ephemeral: false,
	})
	require.NoError(t, err)

	assert.Equal(t, true, captured.Body["ephemeral"],
		"client must override caller's Ephemeral=false to true")
}

func TestIssueToken_PostsToCorrectEndpoint(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	assert.Equal(t, http.MethodPost, captured.Method)
	assert.Equal(t, "/v1/api-keys", captured.Path)
}

func TestIssueToken_SetsAuthHeader(t *testing.T) {
	server, captured := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "test-bearer-token", false, nil)
	_, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	assert.Equal(t, "Bearer test-bearer-token", captured.Header.Get("Authorization"))
	assert.Equal(t, "application/json", captured.Header.Get("Content-Type"))
}

func TestIssueToken_HandlesServerError(t *testing.T) {
	server, _ := newFakeServer(t, http.StatusInternalServerError, `{"error":"internal"}`)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	resp, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})

	assert.Nil(t, resp)
	require.Error(t, err)

	maasErr, ok := err.(*MaaSError)
	require.True(t, ok, "error should be a *MaaSError")
	assert.Equal(t, ErrCodeServerUnavailable, maasErr.Code)
}

func TestIssueToken_HandlesClientError(t *testing.T) {
	server, _ := newFakeServer(t, http.StatusBadRequest, `{"error":"bad request"}`)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	resp, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})

	assert.Nil(t, resp)
	require.Error(t, err)

	maasErr, ok := err.(*MaaSError)
	require.True(t, ok, "error should be a *MaaSError")
	assert.Equal(t, ErrCodeInvalidResponse, maasErr.Code)
}

func TestIssueToken_HandlesSuccessResponse(t *testing.T) {
	server, _ := newFakeServer(t, http.StatusCreated, successResponse)
	defer server.Close()

	client := NewHTTPMaaSClient(server.URL, "tok", false, nil)
	resp, err := client.IssueToken(context.Background(), models.MaaSTokenRequest{})
	require.NoError(t, err)

	assert.Equal(t, "sk-oai-test-key", resp.Key)
	assert.Equal(t, "2099-01-01T00:00:00Z", resp.ExpiresAt)
}
