# InferenceService with direct imagePullSecrets reference (no Connections API)
# User manually created the pull secret
# Requires: connections/direct-pull-secret.yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: isvc-direct-pullsecret
  # No opendatahub.io/connections annotation
spec:
  predictor:
    imagePullSecrets:
      - name: direct-pull-secret
    model:
      modelFormat:
        name: pytorch
      storageUri: oci://quay.io/private-repo/model-image:v1
