kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-dashboard-data-connect-hub-ui
rules:
  - apiGroups:
      - ''
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
  - apiGroups:
      - authorization.k8s.io
    verbs:
      - create
    resources:
      - subjectaccessreviews
  - apiGroups:
      - route.openshift.io
    verbs:
      - get
    resources:
      - routes
  - apiGroups:
      - gateway.networking.k8s.io
    verbs:
      - get
    resources:
      - gateways
