openapi: 3.0.3
info:
  title: AutoRAG REST API
  version: 1.0.0
  description: REST API AutoRAG BFF
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0"
servers:
  - url: "https://localhost:8080"
  - url: "http://localhost:8080"
paths:
  /healthcheck:
    summary: Path targeted for healthcheck purposes.
    description: >-
      The REST endpoint/path used to allow a healthcheck update.
    get:
      tags:
        - K8SOperation
      responses:
        "200":
          description: "Ok"
        "500":
          $ref: "#/components/responses/InternalServerError"
      operationId: healthcheck
      summary: HealthCheck
      description: HealthCheck endpoint.
  /api/v1/namespaces:
    summary: Path used to get available namespaces.
    description: >-
      The REST endpoint/path used to list available namespaces.
    get:
      tags:
        - K8SOperation
      responses:
        "200":
          description: "Ok"
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    description: Metadata about the response
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: default-namespace
        "500":
          $ref: "#/components/responses/InternalServerError"
      operationId: getNamespaces
      summary: Get Available Namespaces
      description: Returns available namespaces in the cluster.
  /api/v1/user:
    summary: Path used to Retrieve a user based on the header.
    description: >-
      The REST endpoint/path used pass all the config information needed for the UI.
    get:
      tags:
        - K8SOperation
      parameters:
        - $ref: "#/components/parameters/kubeflowUserId"
      responses:
        "200":
          $ref: "#/components/responses/ConfigResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"
      operationId: getConfig
      summary: Get configuration info
      description: Gets the configuration information needed for the UI [TBD]

  # =============================================================================
  # PIPELINE RUNS ENDPOINTS
  # =============================================================================

  /api/v1/pipeline-runs:
    summary: Query pipeline runs for a specific pipeline
    description: >-
      Lists pipeline runs from a specified Pipeline Server for a specific pipeline.
      Requires namespace and pipelineServerId parameters for proper isolation.
    get:
      tags:
        - PipelineOperation
      security:
        - Bearer: []
      parameters:
        - $ref: "#/components/parameters/namespace"
        - name: pipelineServerId
          in: query
          required: true
          schema:
            type: string
          description: ID/name of the Pipeline Server (DSPipelineApplication name)
          example: "dspa"
        - name: pipelineId
          in: query
          required: false
          schema:
            type: string
          description: ID of the pipeline to filter runs by
          example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
        - $ref: "#/components/parameters/pageSize"
        - $ref: "#/components/parameters/nextPageToken"
      responses:
        "200":
          $ref: "#/components/responses/PipelineRunsResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      operationId: getPipelineRuns
      summary: Get Pipeline Runs
      description: Returns pipeline runs filtered by pipeline ID

  /api/v1/pipeline-servers:
    summary: List available Pipeline Servers in a namespace
    description: >-
      Returns all Pipeline Servers (DSPipelineApplications) in the specified namespace.
      This allows users to discover which Pipeline Servers are available.
    get:
      tags:
        - PipelineOperation
      security:
        - Bearer: []
      parameters:
        - $ref: "#/components/parameters/namespace"
      responses:
        "200":
          $ref: "#/components/responses/PipelineServersResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"
      operationId: getPipelineServers
      summary: Get Pipeline Servers
      description: Returns all available Pipeline Servers in a namespace
components:
  schemas:
    Config:
      required:
        - userId
        - clusterAdmin
      type: object
      properties:
        userId:
          type: string
          example: user@example.com
        clusterAdmin:
          type: boolean
          example: true

    # Pipeline Run Schemas
    PipelineRun:
      type: object
      description: Kubeflow Pipeline Run information
      required:
        - run_id
        - display_name
        - state
        - created_at
      properties:
        run_id:
          type: string
          description: Unique pipeline run identifier
          example: "abc123-def456-ghi789"
        display_name:
          type: string
          description: Human-readable run name
          example: "AutoRAG Optimization Run 1"
        description:
          type: string
          description: Run description
          example: "Optimizing RAG parameters for dataset X"
        pipeline_version_id:
          type: string
          description: ID of the pipeline version
          example: "pipeline-v1"
        state:
          type: string
          enum: [UNKNOWN, PENDING, RUNNING, SUCCEEDED, SKIPPED, FAILED, ERROR, CANCELED, CANCELING, PAUSED]
          description: Current run state
          example: "SUCCEEDED"
        created_at:
          type: string
          format: date-time
          description: Creation timestamp (ISO 8601)
          example: "2026-02-24T10:30:00Z"
        finished_at:
          type: string
          format: date-time
          description: Completion timestamp (ISO 8601)
          example: "2026-02-24T11:15:00Z"

    PipelineRunsData:
      type: object
      description: List of pipeline runs with pagination support
      required:
        - runs
      properties:
        runs:
          type: array
          description: Array of pipeline runs
          items:
            $ref: '#/components/schemas/PipelineRun'
        total_size:
          type: integer
          format: int32
          description: Total number of runs matching the filter
          example: 42
        next_page_token:
          type: string
          description: Token for retrieving the next page
          example: "eyJwYWdlIjoyfQ=="

    # Pipeline Server Schemas
    PipelineServer:
      type: object
      description: Pipeline Server information
      required:
        - name
        - namespace
        - ready
      properties:
        name:
          type: string
          description: Pipeline Server name (DSPipelineApplication CR name)
          example: "dspa"
        namespace:
          type: string
          description: Kubernetes namespace
          example: "my-namespace"
        ready:
          type: boolean
          description: Whether the Pipeline Server is ready
          example: true
        api_url:
          type: string
          description: Pipeline Server API URL
          example: "https://ds-pipeline-dspa.my-namespace.svc.cluster.local:8443"
        ui_url:
          type: string
          description: Pipeline Server UI URL (if exposed)
          example: "https://ds-pipeline-ui-dspa-my-namespace.apps.cluster.local"

    PipelineServersData:
      type: object
      description: List of available Pipeline Servers
      required:
        - servers
      properties:
        servers:
          type: array
          description: Array of Pipeline Servers
          items:
            $ref: '#/components/schemas/PipelineServer'

    BaseResource:
      allOf:
        - $ref: "#/components/schemas/BaseResourceCreate"
        - type: object
          properties:
            id:
              format: int64
              description: Output only. The unique server generated id of the resource.
              type: string
              readOnly: true
            createTimeSinceEpoch:
              format: int64
              description: Output only. Create time of the resource in millisecond since epoch.
              type: string
              readOnly: true
            lastUpdateTimeSinceEpoch:
              format: int64
              description: |-
                Output only. Last update time of the resource since epoch in millisecond
                since epoch.
              type: string
              readOnly: true
    BaseResourceCreate:
      allOf:
        - $ref: "#/components/schemas/BaseResourceUpdate"
        - type: object
          properties:
            name:
              description: |-
                The client provided name of the artifact. This field is optional. If set,
                it must be unique among all the artifacts of the same artifact type within
                a database instance and cannot be changed once set.
              type: string
    BaseResourceUpdate:
      type: object
      properties:
        customProperties:
          description: User provided custom properties which are not defined by its type.
          type: object
          additionalProperties:
            $ref: "#/components/schemas/MetadataValue"
        description:
          description: |-
            An optional description about the resource.
          type: string
        externalId:
          description: |-
            The external id that come from the clients' system. This field is optional.
            If set, it must be unique among all resources within a database instance.
          type: string

    Error:
      description: Error code and message.
      required:
        - code
        - message
      type: object
      properties:
        code:
          description: Error code
          type: string
        message:
          description: Error message
          type: string
    SortOrder:
      description: Supported sort direction for ordering result entities.
      enum:
        - ASC
        - DESC
      type: string
    OrderByField:
      description: Supported fields for ordering result entities.
      enum:
        - CREATE_TIME
        - LAST_UPDATE_TIME
        - Id
      type: string

  responses:
    NotFound:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
      description: The specified resource was not found
    BadRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
      description: Bad Request parameters
    Unauthorized:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
      description: Unauthorized
    InternalServerError:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
      description: Unexpected internal server error
    ConfigResponse:
      content:
        application/json:
          schema:
            type: object
            properties:
              metadata:
                type: object
                description: Metadata about the response
              data:
                $ref: "#/components/schemas/Config"
      description: A response containing a list of Config entities.

    PipelineRunsResponse:
      description: Successful response containing pipeline runs
      content:
        application/json:
          schema:
            type: object
            properties:
              metadata:
                type: object
                description: Response metadata
              data:
                $ref: '#/components/schemas/PipelineRunsData'
          example:
            metadata: {}
            data:
              runs:
                - run_id: "abc123-def456"
                  display_name: "AutoRAG Optimization Run 1"
                  state: "SUCCEEDED"
                  created_at: "2026-02-24T10:30:00Z"
                  finished_at: "2026-02-24T11:15:00Z"
              total_size: 1
              next_page_token: ""

    PipelineServersResponse:
      description: Successful response containing available Pipeline Servers
      content:
        application/json:
          schema:
            type: object
            properties:
              metadata:
                type: object
                description: Response metadata
              data:
                $ref: '#/components/schemas/PipelineServersData'
          example:
            metadata: {}
            data:
              servers:
                - name: "dspa"
                  namespace: "my-namespace"
                  ready: true
                  api_url: "https://ds-pipeline-dspa.my-namespace.svc.cluster.local:8443"

    ConflictResponse:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
      description: Conflict - Role Binding with the same name already exists

  parameters:
    kubeflowUserId:
      in: header
      name: kubeflow-userid
      schema:
        type: string
      required: true
    id:
      name: id
      description: The ID of resource.
      schema:
        type: string
      in: path
      required: true
    name:
      examples:
        name:
          value: entity-name
      name: name
      description: Name of entity to search.
      schema:
        type: string
      in: query
      required: false
    externalId:
      examples:
        externalId:
          value: "10"
      name: externalId
      description: External ID of entity to search.
      schema:
        type: string
      in: query
      required: false
    parentResourceId:
      examples:
        parentResourceId:
          value: "10"
      name: parentResourceId
      description: ID of the parent resource to use for search.
      schema:
        type: string
      in: query
      required: false
    pageSize:
      examples:
        pageSize:
          value: "100"
      name: pageSize
      description: Number of entities in each page.
      schema:
        type: string
      in: query
      required: false
    nextPageToken:
      name: nextPageToken
      description: Token to use to retrieve next page of results.
      schema:
        type: string
      in: query
      required: false
    orderBy:
      style: form
      explode: true
      examples:
        orderBy:
          value: Id
      name: orderBy
      description: Specifies the order by criteria for listing entities.
      schema:
        $ref: "#/components/schemas/OrderByField"
      in: query
      required: false
    sortOrder:
      style: form
      explode: true
      examples:
        sortOrder:
          value: DESC
      name: sortOrder
      description: "Specifies the sort order for listing entities, defaults to ASC."
      schema:
        $ref: "#/components/schemas/SortOrder"
      in: query
      required: false
    namespace:
      name: namespace
      description: The namespace to filter resources by.
      schema:
        type: string
      in: query
      required: true

  securitySchemes:
    Bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
      description: Bearer JWT scheme
security:
  - Bearer: []
tags:
  - name: K8SOperation
    description: Operation performed in Kubernetes
  - name: PipelineOperation
    description: Operations for querying Kubeflow Pipeline runs
