apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: acceleratorprofiles.opendatahub.io
spec:
  group: opendatahub.io
  scope: Namespaced
  names:
    plural: acceleratorprofiles
    singular: acceleratorprofile
    kind: AcceleratorProfile
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - display-name
                - enabled
                - identifier
              properties:
                display-name:
                  type: string
                enabled:
                  type: boolean
                identifier:
                  type: string
                description:
                  type: string
                modifiedDate:
                  type: string
   