apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: acceleratorprofiles.opendatahub.io
spec:
  group: opendatahub.io
  scope: Namespaced
  names:
    plural: acceleratorprofiles
    singular: acceleratorprofile
    kind: AcceleratorProfile
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - display-name
              properties:
                display-name:
                  type: string
                enabled: true
                identifier: "nvidia.com/gpu" # this is the matching for supported-accelerator annotation
                # optional
                description: "This is nvidia.com/gpu accelerator profile"
                # unknown yet -- tbd if this is metadata annotation
                #modifiedDate: ... (likely iso format)
   