apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: odh-dashboard
  app.kubernetes.io/part-of: odh-dashboard
resources:
- odhdashboardconfigs.opendatahub.io.crd.yaml
- odhquickstarts.console.openshift.io.crd.yaml
- odhdocuments.dashboard.opendatahub.io.crd.yaml
- odhapplications.dashboard.opendatahub.io.crd.yaml
