/* eslint-disable @odh-dashboard/no-restricted-imports -- re-exporting shared types for backward compatibility */
export {
  ConnectionTypeFieldType,
  connectionTypeDataFields,
  AwsKeys,
  AccessTypes,
} from '@odh-dashboard/k8s-core';
export type {
  ConnectionTypeDataFieldTypeUnion,
  ConnectionTypeFieldTypeUnion,
  ConnectionTypeCommonProperties,
  DataField,
  SectionField,
  HiddenField,
  ShortTextField,
  TextField,
  UriField,
  FileField,
  BooleanField,
  DropdownField,
  NumericField,
  ConnectionTypeField,
  ConnectionTypeDataField,
  ConnectionTypeConfigMap,
  ConnectionTypeConfigMapObj,
  ConnectionTypeValueType,
  Connection,
  ConnectionTypeFormData,
  AWSDataEntry,
} from '@odh-dashboard/k8s-core';
