/* eslint-disable @odh-dashboard/no-restricted-imports -- re-exporting shared utilities for backward compatibility */
export {
  isConnectionTypeDataFieldType,
  isConnectionTypeDataField,
  isConnectionType,
  isConnection,
  getConnectionTypeRef,
  toConnectionTypeConfigMapObj,
  toConnectionTypeConfigMap,
  defaultValueToString,
  fieldTypeToString,
  fieldNameToEnvVar,
  ENV_VAR_NAME_REGEX,
  isValidEnvVar,
  ModelServingCompatibleTypes,
  URIConnectionTypeKeys,
  OCIConnectionTypeKeys,
  OCIAccessTypeKey,
  S3ConnectionTypeKeys,
  isModelServingEnvVar,
  getModelServingConnectionTypeName,
  isModelServingCompatible,
  getModelServingCompatibility,
  filterModelServingConnectionTypes,
  getDefaultValues,
  getMRConnectionValues,
  withRequiredFields,
  assembleConnectionSecret,
  parseConnectionSecretValues,
  getConnectionTypeDisplayName,
  filterEnabledConnectionTypes,
  findSectionFields,
  convertObjectStorageSecretData,
  getConnectionProtocolType,
} from '@odh-dashboard/k8s-core';
