apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# NOTE: we use this namespace for consistency with kube-prometheus:
#       https://github.com/prometheus-operator/kube-prometheus/blob/v0.18.0/manifests/setup/namespace.yaml
namespace: monitoring

resources:
- namespace.yaml
- https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.92.0/bundle.yaml