name: Test / Core BFF Tests
on:
  push:
    paths:
      - 'distributions/core-bff/**'
      - '!LICENSE*'
      - '!DOCKERFILE*'
      - '!**.gitignore'
      - '!**.md'

  pull_request:
    paths:
      - 'distributions/core-bff/**'
      - '.github/workflows/core-bff-build.yml'
      - '!LICENSE*'
      - '!DOCKERFILE*'
      - '!**.gitignore'
      - '!**.md'

permissions:
  contents: read

env:
  NODE_VERSION: 22

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.25.0'

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: core-bff root node_modules cache
        id: core-bff-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: distributions/core-bff/node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-core-bff-root-${{ hashFiles('distributions/core-bff/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-core-bff-root-

      - name: core-bff frontend node_modules cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: distributions/core-bff/frontend/node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-core-bff-${{ hashFiles('distributions/core-bff/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-core-bff-

      - name: Lint
        working-directory: distributions/core-bff/bff
        run: make lint

      - name: Build (BFF)
        working-directory: distributions/core-bff/bff
        run: make build

      - name: Test (BFF)
        working-directory: distributions/core-bff/bff
        run: make test

      - name: Install core-bff dependencies
        working-directory: distributions/core-bff
        run: npm install --ignore-scripts --no-package-lock --legacy-peer-deps

      - name: Install frontend dependencies
        working-directory: distributions/core-bff/frontend
        run: npm install
      
      - name: Validate OpenAPI spec
        working-directory: distributions/core-bff
        run: npm run lint:openapi

      - name: Check if there are uncommitted file changes
        working-directory: distributions/core-bff
        run: |
          clean=$(git status --porcelain)
          if [[ -z "$clean" ]]; then
              echo "Empty git status --porcelain: $clean"
          else
              echo "Uncommitted file changes detected: $clean"
              git diff
              exit 1
          fi
