name: Dependabot auto-label

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'opendatahub-io/odh-dashboard'
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v3

      - name: Label with update type
        if: steps.dependabot-metadata.outputs.update-type != ''
        run: gh pr edit "$PR_URL" --add-label "$UPDATE_TYPE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          UPDATE_TYPE: ${{ steps.dependabot-metadata.outputs.update-type }}
