name: Test / Gen AI Frontend Tests
on:
  push:
    paths:
      - 'packages/gen-ai/**'
      - '.github/workflows/gen-ai-frontend-build.yml'
      - '.github/actions/pnpm-setup/**'
      - '!LICENSE*'
      - '!DOCKERFILE*'
      - '!**.gitignore'
      - '!**.md'

  pull_request:
    paths:
      - 'packages/gen-ai/**'
      - '.github/workflows/gen-ai-frontend-build.yml'
      - '.github/actions/pnpm-setup/**'
      - '!LICENSE*'
      - '!DOCKERFILE*'
      - '!**.gitignore'
      - '!**.md'
env:
  NODE_VERSION: 22
jobs:
  test-and-build:
    name: Gen AI Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup pnpm and install dependencies
        uses: ./.github/actions/pnpm-setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: 'packages/gen-ai/bff/go.mod'
          cache-dependency-path: 'packages/gen-ai/bff/go.sum'

      - name: Run tests
        working-directory: packages/gen-ai/frontend
        run: pnpm run test:standalone

      - name: Run clean
        working-directory: packages/gen-ai/frontend
        run: pnpm run clean

      - name: Run build
        working-directory: packages/gen-ai/frontend
        run: pnpm run build:standalone

      - name: Check if there are uncommitted file changes
        working-directory: packages/gen-ai/frontend
        run: |
          clean=$(git status --porcelain)
          if [[ -z "$clean" ]]; then
              echo "Empty git status --porcelain: $clean"
          else
              echo "Uncommitted file changes detected: $clean"
              git diff
              exit 1
          fi

      - name: Upload Cypress results on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: gen-ai-cypress-results
          path: packages/gen-ai/frontend/src/__tests__/cypress/results/
          retention-days: 1
