name: Test / Model Registry Frontend Tests
on:
  push:
    paths:
      - 'packages/model-registry/**'
      - '.github/workflows/model-registry-frontend-tests.yml'
      - '.github/actions/module-caches/**'
      - '!LICENSE*'
      - '!DOCKERFILE*'
      - '!**.gitignore'
      - '!**.md'

  pull_request:
    paths:
      - 'packages/model-registry/**'
      - '.github/workflows/model-registry-frontend-tests.yml'
      - '.github/actions/module-caches/**'
      - '!LICENSE*'
      - '!DOCKERFILE*'
      - '!**.gitignore'
      - '!**.md'

env:
  NODE_VERSION: 22

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Module caches
        uses: ./.github/actions/module-caches
        with:
          node-version: ${{ env.NODE_VERSION }}
          include-cypress: 'true'
      - name: model-registry node_modules cache
        uses: actions/cache@v4
        with:
          path: packages/model-registry/upstream/frontend/node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-model-registry-${{ hashFiles('packages/model-registry/upstream/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-model-registry-

      - name: Install model-registry dependencies
        working-directory: packages/model-registry/upstream/frontend
        run: npm install

      - name: Lint
        working-directory: packages/model-registry/upstream/frontend
        run: npm run test:lint

      - name: Type check
        working-directory: packages/model-registry/upstream/frontend
        run: npm run test:type-check

      - name: Unit tests (Jest)
        working-directory: packages/model-registry/upstream/frontend
        run: npm run test:unit

      - name: Cypress mock tests
        working-directory: packages/model-registry/upstream/frontend
        run: npm run test:cypress-ci

      - name: Run clean
        working-directory: packages/model-registry/upstream/frontend
        run: npm run build:clean

      - name: Run build
        working-directory: packages/model-registry/upstream/frontend
        run: npm run build

      - name: Check if there are uncommitted file changes
        working-directory: packages/model-registry/upstream/frontend
        run: |
          clean=$(git status --porcelain)
          if [[ -z "$clean" ]]; then
              echo "Empty git status --porcelain: $clean"
          else
              echo "Uncommitted file changes detected: $clean"
              git diff
              exit 1
          fi
